//Add organization
export const ORGANIZATION_ADD_REQUEST = 'ORGANIZATION_ADD_REQUEST';
export const ORGANIZATION_ADD_SUCCESS = 'ORGANIZATION_ADD_REQUEST';
export const ORGANIZATION_ADD_FAIL = 'ORGANIZATION_ADD_REQUEST';

//Update organization
export const ORGANIZATION_UPDATE_REQUEST = 'ORGANIZATION_UPDATE_REQUEST';
export const ORGANIZATION_UPDATE_SUCCESS = 'ORGANIZATION_UPDATE_REQUEST';
export const ORGANIZATION_UPDATE_FAIL = 'ORGANIZATION_UPDATE_REQUEST';

//Delete organization
export const ORGANIZATION_DELETE_REQUEST = 'ORGANIZATION_DELETE_REQUEST';
export const ORGANIZATION_DELETE_SUCCESS = 'ORGANIZATION_DELETE_REQUEST';
export const ORGANIZATION_DELETE_FAIL = 'ORGANIZATION_DELETE_REQUEST';

//Read organization
export const ORGANIZATION_DETAILS_REQUEST = 'ORGANIZATION_DETAILS_REQUEST';
export const ORGANIZATION_DETAILS_SUCCESS = 'ORGANIZATION_DETAILS_REQUEST';
export const ORGANIZATION_DETAILS_FAIL = 'ORGANIZATION_DETAILS_REQUEST';

//Get list of organization
export const ORGANIZATION_LIST_REQUEST = 'ORGANIZATION_LIST_REQUEST';
export const ORGANIZATION_LIST_SUCCESS = 'ORGANIZATION_LIST_REQUEST';
export const ORGANIZATION_LIST_FAIL = 'ORGANIZATION_LIST_REQUEST';
