//Add organization
export const ORGANIZATION_ADD_REQUEST = 'ORGANIZATION_ADD_REQUEST';
export const ORGANIZATION_ADD_SUCCESS = 'ORGANIZATION_ADD_SUCCESS';
export const ORGANIZATION_ADD_FAIL = 'ORGANIZATION_ADD_FAIL';
export const ORGANIZATION_ADD_RESET = 'ORGANIZATION_ADD_RESET';

//Get organization details
export const ORGANIZATION_DETAILS_REQUEST = 'ORGANIZATION_DETAILS_REQUEST';
export const ORGANIZATION_DETAILS_SUCCESS = 'ORGANIZATION_DETAILS_SUCCESS';
export const ORGANIZATION_DETAILS_FAIL = 'ORGANIZATION_DETAILS_FAIL';
export const ORGANIZATION_DETAILS_RESET = 'ORGANIZATION_DETAILS_RESET';

//Update organization
export const ORGANIZATION_UPDATE_REQUEST = 'ORGANIZATION_UPDATE_REQUEST';
export const ORGANIZATION_UPDATE_SUCCESS = 'ORGANIZATION_UPDATE_SUCCESS';
export const ORGANIZATION_UPDATE_FAIL = 'ORGANIZATION_UPDATE_FAIL';
export const ORGANIZATION_UPDATE_RESET = 'ORGANIZATION_UPDATE_RESET';

//Delete organization
export const ORGANIZATION_DELETE_REQUEST = 'ORGANIZATION_DELETE_REQUEST';
export const ORGANIZATION_DELETE_SUCCESS = 'ORGANIZATION_DELETE_SUCCESS';
export const ORGANIZATION_DELETE_FAIL = 'ORGANIZATION_DELETE_FAIL';
export const ORGANIZATION_DELETE_RESET = 'ORGANIZATION_DELETE_RESET';

//Get list of organization for a project
export const ORGANIZATION_LIST_REQUEST = 'ORGANIZATION_LIST_REQUEST';
export const ORGANIZATION_LIST_SUCCESS = 'ORGANIZATION_LIST_SUCCESS';
export const ORGANIZATION_LIST_FAIL = 'ORGANIZATION_LIST_FAIL';
export const ORGANIZATION_LIST_RESET = 'ORGANIZATION_LIST_RESET';

//Get list of organizations for a stakeholder
export const ORGANIZATION_STAKEHOLDER_LIST_REQUEST =
	'ORGANIZATION_STAKEHOLDER_LIST_REQUEST';
export const ORGANIZATION_STAKEHOLDER_LIST_SUCCESS =
	'ORGANIZATION_STAKEHOLDER_LIST_SUCCESS';
export const ORGANIZATION_STAKEHOLDER_LIST_FAIL =
	'ORGANIZATION_STAKEHOLDER_LIST_FAIL';
export const ORGANIZATION_STAKEHOLDER_LIST_RESET =
	'ORGANIZATION_STAKEHOLDER_LIST_RESET';
