export const PROJECT_LIST_REQUEST = 'PROJECT_LIST_REQUEST';
export const PROJECT_LIST_SUCCESS = 'PROJECT_LIST_SUCCESS';
export const PROJECT_LIST_FAIL = 'PROJECT_LIST_FAIL';
export const PROJECT_LIST_RESET = 'PROJECT_LIST_RESET';

export const PROJECT_DETAILS_REQUEST = 'PROJECT_DETAILS_REQUEST';
export const PROJECT_DETAILS_SUCCESS = 'PROJECT_DETAILS_SUCCESS';
export const PROJECT_DETAILS_FAIL = 'PROJECT_DETAILS_FAIL';

export const PROJECT_UPDATE_REQUEST = 'PROJECT_UPDATE_REQUEST';
export const PROJECT_UPDATE_SUCCESS = 'PROJECT_UPDATE_SUCCESS';
export const PROJECT_UPDATE_FAIL = 'PROJECT_UPDATE_FAIL';
export const PROJECT_UPDATE_RESET = 'PROJECT_UPDATE_RESET';

export const PROJECT_ADD_REQUEST = 'PROJECT_ADD_REQUEST';
export const PROJECT_ADD_SUCCESS = 'PROJECT_ADD_SUCCESS';
export const PROJECT_ADD_FAIL = 'PROJECT_ADD_FAIL';

export const PROJECT_USER_REQUEST = 'PROJECT_USER_REQUEST';
export const PROJECT_USER_SUCCESS = 'PROJECT_USER_SUCCESS';
export const PROJECT_USER_FAIL = 'PROJECT_USER_FAIL';
export const PROJECT_USER_RESET = 'PROJECT_USER_RESET';

export const PROJECT_ASSIGNMENT_REQUEST = 'PROJECT_ASSIGNMENT_REQUEST';
export const PROJECT_ASSIGNMENT_SUCCESS = 'PROJECT_ASSIGNMENT_SUCCESS';
export const PROJECT_ASSIGNMENT_FAIL = 'PROJECT_ASSIGNMENT_FAIL';
export const PROJECT_ASSIGNMENT_RESET = 'PROJECT_ASSIGNMENT_RESET';
