//add stakeholder
export const STAKEHOLDER_ADD_REQUEST = 'STAKEHOLDER_ADD_REQUEST';
export const STAKEHOLDER_ADD_SUCCESS = 'STAKEHOLDER_ADD_SUCCESS';
export const STAKEHOLDER_ADD_FAIL = 'STAKEHOLDER_ADD_FAIL';
export const STAKEHOLDER_ADD_RESET = 'STAKEHOLDER_ADD_FAIL';

//get stakeholder details
export const STAKEHOLDER_DETAILS_REQUEST = 'STAKEHOLDER_DETAILS_REQUEST';
export const STAKEHOLDER_DETAILS_SUCCESS = 'STAKEHOLDER_DETAILS_SUCCESS';
export const STAKEHOLDER_DETAILS_FAIL = 'STAKEHOLDER_DETAILS_FAIL';

//update stakeholder
export const STAKEHOLDER_UPDATE_REQUEST = 'STAKEHOLDER_UPDATE_REQUEST';
export const STAKEHOLDER_UPDATE_SUCCESS = 'STAKEHOLDER_UPDATE_SUCCESS';
export const STAKEHOLDER_UPDATE_FAIL = 'STAKEHOLDER_UPDATE_FAIL';
export const STAKEHOLDER_UPDATE_RESET = 'STAKEHOLDER_UPDATE_RESET';

//delete stakeholder
export const STAKEHOLDER_DELETE_REQUEST = 'STAKEHOLDER_DELETE_REQUEST';
export const STAKEHOLDER_DELETE_SUCCESS = 'STAKEHOLDER_DELETE_SUCCESS';
export const STAKEHOLDER_DELETE_FAIL = 'STAKEHOLDER_DELETE_FAIL';
export const STAKEHOLDER_DELETE_RESET = 'STAKEHOLDER_DELETE_RESET';

//get stakeholder list
export const STAKEHOLDER_LIST_REQUEST = 'STAKEHOLDER_LIST_REQUEST';
export const STAKEHOLDER_LIST_SUCCESS = 'STAKEHOLDER_LIST_SUCCESS';
export const STAKEHOLDER_LIST_FAIL = 'STAKEHOLDER_LIST_FAIL';
